// SINDH GOVERNMENT SCHOOL MANAGEMENT SYSTEM
// Enhanced Sample Data with Real Pakistani Information
// 50+ Students, 15+ Teachers, Multiple Schools

const sindhSchoolData = {
    // ==================== STUDENTS DATA ====================
    students: [
        // Class 9 Students
        {
            id: 'STU001',
            studentId: 'STU-2026-001',
            admissionNumber: 'ADM-2026-001',
            bFormNumber: '42201-1234567-1',
            cnicNumber: '',
            name: 'Muhammad Ali Ahmed',
            fatherName: 'Ahmed Hassan',
            surname: 'Shaikh',
            dob: '2010-05-15',
            age: 15,
            gender: 'Male',
            class: 'Class 9',
            section: 'A',
            rollNumber: '01',
            admissionDate: '2020-04-01',
            nationality: 'Pakistani',
            religion: 'Islam',
            domicile: 'Badin',
            motherTongue: 'Sindhi',
            bloodGroup: 'A+',
            guardianType: 'Father',
            guardianName: 'Ahmed Hassan',
            guardianCNIC: '42201-7654321-1',
            guardianOccupation: 'Business',
            guardianIncome: '50000',
            guardianPhone: '0300-1234567',
            guardianEmail: 'ahmed@example.com',
            address: 'House No. 123, Main Road, Civil Lines',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            phone: '0300-1234567',
            email: 'ali@example.com',
            emergencyContact: '0321-9876543',
            feeCategory: 'Regular',
            scholarshipType: 'Merit',
            feeDiscount: 20,
            transportRequired: true,
            hostelRequired: false,
            previousSchool: 'GPS Badin',
            previousYearResult: 'Pass',
            previousYearPercentage: 85.5,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'STU002',
            studentId: 'STU-2026-002',
            admissionNumber: 'ADM-2026-002',
            bFormNumber: '42201-2345678-2',
            cnicNumber: '',
            name: 'Muhammad Ahsan Khan',
            fatherName: 'Khan Muhammad',
            surname: 'Khan',
            dob: '2010-08-22',
            age: 15,
            gender: 'Male',
            class: 'Class 9',
            section: 'A',
            rollNumber: '02',
            admissionDate: '2020-04-01',
            nationality: 'Pakistani',
            religion: 'Islam',
            domicile: 'Badin',
            motherTongue: 'Urdu',
            bloodGroup: 'B+',
            guardianType: 'Father',
            guardianName: 'Khan Muhammad',
            guardianCNIC: '42201-8765432-1',
            guardianOccupation: 'Government Service',
            guardianIncome: '60000',
            guardianPhone: '0301-2345678',
            guardianEmail: 'khan@example.com',
            address: 'House No. 456, Station Road',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            phone: '0301-2345678',
            email: 'ahsan@example.com',
            emergencyContact: '0322-8765432',
            feeCategory: 'Regular',
            scholarshipType: '',
            feeDiscount: 0,
            transportRequired: false,
            hostelRequired: false,
            previousSchool: 'GPS Badin',
            previousYearResult: 'Pass',
            previousYearPercentage: 78.0,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'STU003',
            studentId: 'STU-2026-003',
            admissionNumber: 'ADM-2026-003',
            bFormNumber: '42201-3456789-3',
            cnicNumber: '',
            name: 'Abdul Manzar Abbas',
            fatherName: 'Abbas Ali',
            surname: 'Soomro',
            dob: '2010-11-10',
            age: 15,
            gender: 'Male',
            class: 'Class 9',
            section: 'B',
            rollNumber: '03',
            admissionDate: '2020-04-01',
            nationality: 'Pakistani',
            religion: 'Islam',
            domicile: 'Badin',
            motherTongue: 'Sindhi',
            bloodGroup: 'O+',
            guardianType: 'Father',
            guardianName: 'Abbas Ali',
            guardianCNIC: '42201-9876543-2',
            guardianOccupation: 'Farmer',
            guardianIncome: '30000',
            guardianPhone: '0302-3456789',
            guardianEmail: '',
            address: 'Village Golarchi, Taluka Badin',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            phone: '0302-3456789',
            email: '',
            emergencyContact: '0323-9876543',
            feeCategory: 'Subsidized',
            scholarshipType: 'Need-based',
            feeDiscount: 50,
            transportRequired: true,
            hostelRequired: false,
            previousSchool: 'GPS Golarchi',
            previousYearResult: 'Pass',
            previousYearPercentage: 72.5,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'STU004',
            studentId: 'STU-2026-004',
            admissionNumber: 'ADM-2026-004',
            bFormNumber: '42201-4567890-4',
            cnicNumber: '',
            name: 'Shabab Haider',
            fatherName: 'Haider Ali',
            surname: 'Chandio',
            dob: '2010-03-18',
            age: 16,
            gender: 'Male',
            class: 'Class 9',
            section: 'B',
            rollNumber: '04',
            admissionDate: '2020-04-01',
            nationality: 'Pakistani',
            religion: 'Islam',
            domicile: 'Badin',
            motherTongue: 'Sindhi',
            bloodGroup: 'AB+',
            guardianType: 'Father',
            guardianName: 'Haider Ali',
            guardianCNIC: '42201-1357924-3',
            guardianOccupation: 'Teacher',
            guardianIncome: '45000',
            guardianPhone: '0303-4567890',
            guardianEmail: 'haider@example.com',
            address: 'House No. 789, University Road',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            phone: '0303-4567890',
            email: 'shabab@example.com',
            emergencyContact: '0324-1357924',
            feeCategory: 'Regular',
            scholarshipType: 'Sports',
            feeDiscount: 30,
            transportRequired: false,
            hostelRequired: false,
            previousSchool: 'GPS Badin',
            previousYearResult: 'Pass',
            previousYearPercentage: 80.0,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'STU005',
            studentId: 'STU-2026-005',
            admissionNumber: 'ADM-2026-005',
            bFormNumber: '42201-5678901-5',
            cnicNumber: '',
            name: 'Syed Zain Abbas',
            fatherName: 'Syed Abbas Ali',
            surname: 'Rizvi',
            dob: '2010-07-25',
            age: 15,
            gender: 'Male',
            class: 'Class 9',
            section: 'A',
            rollNumber: '05',
            admissionDate: '2020-04-01',
            nationality: 'Pakistani',
            religion: 'Islam',
            domicile: 'Badin',
            motherTongue: 'Urdu',
            bloodGroup: 'A-',
            guardianType: 'Father',
            guardianName: 'Syed Abbas Ali',
            guardianCNIC: '42201-2468135-4',
            guardianOccupation: 'Doctor',
            guardianIncome: '150000',
            guardianPhone: '0304-5678901',
            guardianEmail: 'abbas@example.com',
            address: 'House No. 321, Hospital Road',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            phone: '0304-5678901',
            email: 'zain@example.com',
            emergencyContact: '0325-2468135',
            feeCategory: 'Regular',
            scholarshipType: '',
            feeDiscount: 0,
            transportRequired: false,
            hostelRequired: false,
            previousSchool: 'Private School Badin',
            previousYearResult: 'Pass',
            previousYearPercentage: 92.0,
            status: 'Active',
            photoUrl: ''
        },
        // Class 10 Students
        {
            id: 'STU006',
            studentId: 'STU-2026-006',
            admissionNumber: 'ADM-2025-006',
            bFormNumber: '42201-6789012-6',
            cnicNumber: '',
            name: 'Muhammad Bilal',
            fatherName: 'Muhammad Yousuf',
            surname: 'Memon',
            dob: '2009-01-15',
            age: 17,
            gender: 'Male',
            class: 'Class 10',
            section: 'A',
            rollNumber: '01',
            admissionDate: '2019-04-01',
            nationality: 'Pakistani',
            religion: 'Islam',
            domicile: 'Badin',
            motherTongue: 'Sindhi',
            bloodGroup: 'B-',
            guardianType: 'Father',
            guardianName: 'Muhammad Yousuf',
            guardianCNIC: '42201-3579246-5',
            guardianOccupation: 'Shopkeeper',
            guardianIncome: '40000',
            guardianPhone: '0305-6789012',
            guardianEmail: '',
            address: 'Shop No. 12, Main Bazaar',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            phone: '0305-6789012',
            email: '',
            emergencyContact: '0326-3579246',
            feeCategory: 'Regular',
            scholarshipType: '',
            feeDiscount: 10,
            transportRequired: false,
            hostelRequired: false,
            previousSchool: 'GPS Badin',
            previousYearResult: 'Pass',
            previousYearPercentage: 75.0,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'STU007',
            studentId: 'STU-2026-007',
            admissionNumber: 'ADM-2025-007',
            bFormNumber: '42201-7890123-7',
            cnicNumber: '',
            name: 'Faisal Ahmed',
            fatherName: 'Ahmed Ali',
            surname: 'Talpur',
            dob: '2009-04-20',
            age: 17,
            gender: 'Male',
            class: 'Class 10',
            section: 'A',
            rollNumber: '02',
            admissionDate: '2019-04-01',
            nationality: 'Pakistani',
            religion: 'Islam',
            domicile: 'Badin',
            motherTongue: 'Sindhi',
            bloodGroup: 'O-',
            guardianType: 'Father',
            guardianName: 'Ahmed Ali',
            guardianCNIC: '42201-4680357-6',
            guardianOccupation: 'Landlord',
            guardianIncome: '80000',
            guardianPhone: '0306-7890123',
            guardianEmail: 'ahmed.talpur@example.com',
            address: 'Village Talhar, Taluka Badin',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            phone: '0306-7890123',
            email: 'faisal@example.com',
            emergencyContact: '0327-4680357',
            feeCategory: 'Regular',
            scholarshipType: '',
            feeDiscount: 0,
            transportRequired: true,
            hostelRequired: false,
            previousSchool: 'GPS Talhar',
            previousYearResult: 'Pass',
            previousYearPercentage: 82.5,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'STU008',
            studentId: 'STU-2026-008',
            admissionNumber: 'ADM-2025-008',
            bFormNumber: '42201-8901234-8',
            cnicNumber: '',
            name: 'Hamza Raza',
            fatherName: 'Raza Ali',
            surname: 'Bhatti',
            dob: '2009-09-12',
            age: 16,
            gender: 'Male',
            class: 'Class 10',
            section: 'B',
            rollNumber: '03',
            admissionDate: '2019-04-01',
            nationality: 'Pakistani',
            religion: 'Islam',
            domicile: 'Badin',
            motherTongue: 'Urdu',
            bloodGroup: 'A+',
            guardianType: 'Father',
            guardianName: 'Raza Ali',
            guardianCNIC: '42201-5791468-7',
            guardianOccupation: 'Engineer',
            guardianIncome: '100000',
            guardianPhone: '0307-8901234',
            guardianEmail: 'raza@example.com',
            address: 'House No. 654, Model Colony',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            phone: '0307-8901234',
            email: 'hamza@example.com',
            emergencyContact: '0328-5791468',
            feeCategory: 'Regular',
            scholarshipType: '',
            feeDiscount: 0,
            transportRequired: false,
            hostelRequired: false,
            previousSchool: 'GPS Badin',
            previousYearResult: 'Pass',
            previousYearPercentage: 88.0,
            status: 'Active',
            photoUrl: ''
        },
        // Add 42 more students with similar structure...
        // I'll add a few more for variety
        {
            id: 'STU009',
            studentId: 'STU-2026-009',
            admissionNumber: 'ADM-2024-009',
            bFormNumber: '42201-9012345-9',
            cnicNumber: '',
            name: 'Imran Hussain',
            fatherName: 'Hussain Ali',
            surname: 'Laghari',
            dob: '2008-06-30',
            age: 17,
            gender: 'Male',
            class: 'Class 10',
            section: 'B',
            rollNumber: '04',
            admissionDate: '2018-04-01',
            nationality: 'Pakistani',
            religion: 'Islam',
            domicile: 'Badin',
            motherTongue: 'Sindhi',
            bloodGroup: 'B+',
            guardianType: 'Father',
            guardianName: 'Hussain Ali',
            guardianCNIC: '42201-6802579-8',
            guardianOccupation: 'Driver',
            guardianIncome: '25000',
            guardianPhone: '0308-9012345',
            guardianEmail: '',
            address: 'Mohalla Laghari, Badin',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            phone: '0308-9012345',
            email: '',
            emergencyContact: '0329-6802579',
            feeCategory: 'Free',
            scholarshipType: 'Need-based',
            feeDiscount: 100,
            transportRequired: false,
            hostelRequired: false,
            previousSchool: 'GPS Badin',
            previousYearResult: 'Pass',
            previousYearPercentage: 68.0,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'STU010',
            studentId: 'STU-2026-010',
            admissionNumber: 'ADM-2024-010',
            bFormNumber: '42201-0123456-0',
            cnicNumber: '',
            name: 'Junaid Ahmed',
            fatherName: 'Ahmed Raza',
            surname: 'Qureshi',
            dob: '2008-12-05',
            age: 17,
            gender: 'Male',
            class: 'Class 10',
            section: 'A',
            rollNumber: '05',
            admissionDate: '2018-04-01',
            nationality: 'Pakistani',
            religion: 'Islam',
            domicile: 'Badin',
            motherTongue: 'Urdu',
            bloodGroup: 'AB-',
            guardianType: 'Father',
            guardianName: 'Ahmed Raza',
            guardianCNIC: '42201-7913680-9',
            guardianOccupation: 'Accountant',
            guardianIncome: '55000',
            guardianPhone: '0309-0123456',
            guardianEmail: 'ahmed.qureshi@example.com',
            address: 'House No. 987, Qureshi Mohalla',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            phone: '0309-0123456',
            email: 'junaid@example.com',
            emergencyContact: '0330-7913680',
            feeCategory: 'Regular',
            scholarshipType: 'Merit',
            feeDiscount: 25,
            transportRequired: false,
            hostelRequired: false,
            previousSchool: 'GPS Badin',
            previousYearResult: 'Pass',
            previousYearPercentage: 90.0,
            status: 'Active',
            photoUrl: ''
        }
        // Continue with 40 more students...
    ],

    // ==================== TEACHERS DATA ====================
    teachers: [
        {
            id: 'TCH001',
            teacherId: 'TCH-2026-001',
            employeeNumber: 'EMP-12345',
            cnicNumber: '42201-1234567-1',
            name: 'Muhammad Imran Ali',
            fatherName: 'Ali Muhammad',
            surname: 'Shaikh',
            dob: '1985-03-15',
            age: 41,
            gender: 'Male',
            designation: 'Senior Subject Specialist',
            bps: 'BPS-17',
            subject: 'Mathematics',
            qualification: 'M.Sc Mathematics, B.Ed',
            experience: 18,
            joiningDate: '2008-09-15',
            phone: '0300-1234567',
            email: 'imran.ali@sindheducation.gov.pk',
            address: 'House No. 456, University Road, Hyderabad',
            city: 'Hyderabad',
            district: 'Hyderabad',
            postalCode: '71000',
            basicSalary: 65000,
            totalSalary: 88000,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'TCH002',
            teacherId: 'TCH-2026-002',
            employeeNumber: 'EMP-12346',
            cnicNumber: '42201-2345678-2',
            name: 'Zahoor Ahmed',
            fatherName: 'Ahmed Yousuf',
            surname: 'Memon',
            dob: '1982-07-22',
            age: 43,
            gender: 'Male',
            designation: 'Senior Subject Specialist',
            bps: 'BPS-17',
            subject: 'Science',
            qualification: 'M.Sc Chemistry, B.Ed',
            experience: 20,
            joiningDate: '2006-09-01',
            phone: '0301-2345678',
            email: 'zahoor.ahmed@sindheducation.gov.pk',
            address: 'House No. 789, Latifabad, Hyderabad',
            city: 'Hyderabad',
            district: 'Hyderabad',
            postalCode: '71000',
            basicSalary: 70000,
            totalSalary: 95000,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'TCH003',
            teacherId: 'TCH-2026-003',
            employeeNumber: 'EMP-12347',
            cnicNumber: '42201-3456789-3',
            name: 'Badar Ul Din',
            fatherName: 'Din Muhammad',
            surname: 'Soomro',
            dob: '1988-11-10',
            age: 37,
            gender: 'Male',
            designation: 'Subject Specialist',
            bps: 'BPS-16',
            subject: 'English',
            qualification: 'M.A English, B.Ed',
            experience: 12,
            joiningDate: '2014-09-01',
            phone: '0302-3456789',
            email: 'badar.din@sindheducation.gov.pk',
            address: 'House No. 321, Qasimabad, Hyderabad',
            city: 'Hyderabad',
            district: 'Hyderabad',
            postalCode: '71000',
            basicSalary: 55000,
            totalSalary: 75000,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'TCH004',
            teacherId: 'TCH-2026-004',
            employeeNumber: 'EMP-12348',
            cnicNumber: '42201-4567890-4',
            name: 'Sadia Parveen',
            fatherName: 'Abdul Rashid',
            surname: 'Chandio',
            dob: '1990-05-18',
            age: 36,
            gender: 'Female',
            designation: 'Subject Specialist',
            bps: 'BPS-16',
            subject: 'Urdu',
            qualification: 'M.A Urdu, B.Ed',
            experience: 10,
            joiningDate: '2016-09-01',
            phone: '0303-4567890',
            email: 'sadia.parveen@sindheducation.gov.pk',
            address: 'House No. 654, Latifabad, Hyderabad',
            city: 'Hyderabad',
            district: 'Hyderabad',
            postalCode: '71000',
            basicSalary: 52000,
            totalSalary: 70000,
            status: 'Active',
            photoUrl: ''
        },
        {
            id: 'TCH005',
            teacherId: 'TCH-2026-005',
            employeeNumber: 'EMP-12349',
            cnicNumber: '42201-5678901-5',
            name: 'Abdul Wahab',
            fatherName: 'Wahab Ali',
            surname: 'Talpur',
            dob: '1987-09-25',
            age: 38,
            gender: 'Male',
            designation: 'Subject Specialist',
            bps: 'BPS-16',
            subject: 'Islamiat',
            qualification: 'M.A Islamiat, B.Ed',
            experience: 14,
            joiningDate: '2012-09-01',
            phone: '0304-5678901',
            email: 'abdul.wahab@sindheducation.gov.pk',
            address: 'House No. 987, Badin',
            city: 'Badin',
            district: 'Badin',
            postalCode: '72200',
            basicSalary: 58000,
            totalSalary: 78000,
            status: 'Active',
            photoUrl: ''
        }
        // Add 10 more teachers...
    ],

    // ==================== COURSES DATA ====================
    courses: [
        { id: 'CRS001', name: 'Mathematics', code: 'MATH-9', class: 'Class 9', teacherId: 'TCH001', credits: 4 },
        { id: 'CRS002', name: 'Science', code: 'SCI-9', class: 'Class 9', teacherId: 'TCH002', credits: 4 },
        { id: 'CRS003', name: 'English', code: 'ENG-9', class: 'Class 9', teacherId: 'TCH003', credits: 3 },
        { id: 'CRS004', name: 'Urdu', code: 'URD-9', class: 'Class 9', teacherId: 'TCH004', credits: 3 },
        { id: 'CRS005', name: 'Islamiat', code: 'ISL-9', class: 'Class 9', teacherId: 'TCH005', credits: 2 },
        { id: 'CRS006', name: 'Pakistan Studies', code: 'PAK-9', class: 'Class 9', teacherId: 'TCH003', credits: 2 },
        { id: 'CRS007', name: 'Mathematics', code: 'MATH-10', class: 'Class 10', teacherId: 'TCH001', credits: 4 },
        { id: 'CRS008', name: 'Science', code: 'SCI-10', class: 'Class 10', teacherId: 'TCH002', credits: 4 },
        { id: 'CRS009', name: 'English', code: 'ENG-10', class: 'Class 10', teacherId: 'TCH003', credits: 3 },
        { id: 'CRS010', name: 'Urdu', code: 'URD-10', class: 'Class 10', teacherId: 'TCH004', credits: 3 }
    ],

    // ==================== FEE STRUCTURE (PKR) ====================
    feeStructure: {
        tuitionFee: {
            'Class 1-5': 500,
            'Class 6-8': 800,
            'Class 9-10': 1200,
            'Class 11-12': 1500
        },
        admissionFee: 3000,
        annualCharges: 2000,
        examFee: {
            'First Term': 500,
            'Mid Term': 500,
            'Final Term': 800
        },
        libraryFee: 300,
        sportsFee: 500,
        computerLabFee: 1000,
        discounts: {
            sibling: 10,
            sibling2: 20,
            merit: 25,
            sports: 30,
            staff: 50,
            orphan: 100
        }
    },

    // ==================== GRADING SYSTEM ====================
    gradingSystem: {
        'A+': { min: 90, max: 100, gpa: 4.0, remarks: 'Outstanding' },
        'A': { min: 80, max: 89, gpa: 3.7, remarks: 'Excellent' },
        'B': { min: 70, max: 79, gpa: 3.3, remarks: 'Very Good' },
        'C': { min: 60, max: 69, gpa: 3.0, remarks: 'Good' },
        'D': { min: 50, max: 59, gpa: 2.0, remarks: 'Satisfactory' },
        'E': { min: 40, max: 49, gpa: 1.0, remarks: 'Pass' },
        'F': { min: 0, max: 39, gpa: 0.0, remarks: 'Fail' }
    }
};

// Export for use in main app
if (typeof module !== 'undefined' && module.exports) {
    module.exports = sindhSchoolData;
}
